name: Execute API Proxy and Deploy

on:
  schedule:
    - cron: '*/30 * * * *' # Запуск каждые 30 минут
  workflow_dispatch: # Возможность запустить руками кнопку "Run workflow"

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Fetch target data
        run: node proxy.js

      - name: Upload static artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: '.' # Загружаем корень репозитория (где лежит наш data.json)

  deploy:
    needs: build-and-deploy
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
